# Generated by Django 3.1.2 on 2020-10-25 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0002_auto_20201025_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidadespsr',
            name='Psr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PSR.cadastropsr'),
            preserve_default=False,
        ),
    ]
