# Generated by Django 3.1.2 on 2020-10-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0003_necessidadespsr_psr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidadespsr',
            name='Agua',
            field=models.CharField(blank=True, choices=[('MEIOLITRO', '500 ml'), ('1L', '1 L'), ('2L', '2 L'), ('5L', '5 L')], max_length=50),
        ),
        migrations.AlterField(
            model_name='necessidadespsr',
            name='Comida',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='necessidadespsr',
            name='Higiene',
            field=models.CharField(blank=True, choices=[('SABONETE', 'Sabonete'), ('XAMPU/CONDICIONADOR', 'Xampu/Condicionador'), ('ESCOVA/PASTA DE DENTE', 'Escova/Pasta de dente'), ('ALCOOL', 'Alcool'), ('FRAUDA', 'Frauda'), ('ABSORVENTE', 'Absorvente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='necessidadespsr',
            name='Outros',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='necessidadespsr',
            name='Roupas',
            field=models.CharField(blank=True, choices=[('CAMISA', 'Camisa(s)'), ('CALÇAS', 'Calça(s)/Bermuda(s)/Short(s)'), ('CALÇADOS', 'Calçado(s)')], default='CAMISA', max_length=50),
        ),
        migrations.AlterField(
            model_name='necessidadespsr',
            name='Saude',
            field=models.CharField(blank=True, choices=[('REMEDIOS', 'Remedios'), ('ASSISTENCIA MEDICA', 'Assistencia Medica'), ('ASSITENCIA VETERINARIA', 'Assistencia Veterinaria')], default='REMEDIOS', max_length=50),
        ),
    ]
