# Generated by Django 3.1.2 on 2020-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0004_auto_20201025_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropsr',
            name='Hora',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='necessidadespsr',
            name='Hora',
            field=models.DateField(auto_now=True),
        ),
    ]
