# Generated by Django 3.1.2 on 2020-10-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0005_auto_20201028_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropsr',
            name='Hora',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='necessidadespsr',
            name='Hora',
            field=models.DateField(),
        ),
    ]
