# Generated by Django 3.1.2 on 2020-10-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0007_auto_20201028_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastropsr',
            old_name='Hora',
            new_name='Dia',
        ),
    ]
