# Generated by Django 3.1.2 on 2020-10-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0009_auto_20201028_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastropsr',
            old_name='Dia',
            new_name='Hora',
        ),
        migrations.RenameField(
            model_name='necessidadespsr',
            old_name='Dia',
            new_name='Hora',
        ),
    ]
