# Generated by Django 3.1.2 on 2020-10-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0010_auto_20201028_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastropsr',
            old_name='Hora',
            new_name='Dia',
        ),
        migrations.RenameField(
            model_name='necessidadespsr',
            old_name='Hora',
            new_name='Dia',
        ),
    ]
