# Generated by Django 3.1.2 on 2020-10-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0011_auto_20201028_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropsr',
            name='Apelido',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cadastropsr',
            name='Nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
