# Generated by Django 3.1.2 on 2020-11-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0013_auto_20201028_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastropsr',
            old_name='Dia',
            new_name='Hora',
        ),
    ]
