# Generated by Django 3.1.2 on 2020-11-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSR', '0014_auto_20201122_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, default='', max_length=120)),
                ('longitude', models.CharField(blank=True, default='', max_length=120)),
                ('id_PSR', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
    ]
